export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED='password_changed'
export const SIGN_FAILED='sign_failed'
export const DATA_FETCHED='data_fetched'
export const LOGIN_SUCCESS='login_success'